services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: chessapp-backend:ci
    ports:
      - "3000:3000"
    environment:
      - BASE_URL=${BASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:3000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: chess
        MYSQL_USER: chess
        MYSQL_PASSWORD: chesspass

    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -pexample" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
